language: python

python:
  - "3.3"

# Setup miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.3.0-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda create --yes -n cyphi python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate cyphi
  # Not yet available for py3 in anaconda 
  - pip install -r test_requirements.txt
  - pip freeze
  - python setup.py install

# Run tests
script: py.test
