name: pyphi
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - jupyterlab
  - jupyterlab-lsp
  - python-lsp-server
  - nodejs
  - python=3.9
  - pip
  - pip:
      - -e -r requirements.txt
      - blackcellmagic
